services:
  app:
    container_name: shaberumon-app
    build:
      context: .
      dockerfile: etc/docker/app/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - APPLICATION_ID=${APPLICATION_ID}
      - VOICEVOX_ENDPOINT=${VOICEVOX_ENDPOINT:-http://voicevox:50021}
      - MONGODB_ENDPOINT=${MONGODB_ENDPOINT:-mongodb://mongodb:27017}
      - CHOKIDAR_USEPOLLING=${CHOKIDAR_USEPOLLING:-0}
    links:
      - voicevox
      - mongodb
  voicevox:
    container_name: shaberumon-voicevox
    image: voicevox/voicevox_engine
  mongodb:
    container_name: shaberumon-mongodb
    image: mongo

volumes:
  node_modules:
    driver: 'local'
