version: '3'
services:
  app:
    container_name: shaberumon-app
    build:
      context: .
      dockerfile: etc/docker/app/Dockerfile
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    env_file: .env
    links:
      - voicevox
      - mongodb
  voicevox:
    container_name: shaberumon-voicevox
    image: voicevox/voicevox_engine
  mongodb:
    container_name: shaberumon-mongodb
    image: mongo

volumes:
  node_modules:
    driver: 'local'